embedding:
  service: ollama
  api_base: http://host.docker.internal:11434
  model_name: all-minilm

document_collections:
  - directory: /ObsidianVault
    collection_name: obsidian_notes

logging:
  level: INFO

chroma:
  host: host.docker.internal
  port: 8001

mcp:
  port: 8002
